//Document Actions
export const GET_DOCUMENTS = "GET_DOCUMENTS";
export const FILTER_BY_STATUS = "FILTER_BY_STATUS";
export const FILTER_BY_TYPE = "FILTER_BY_TYPE";
export const FILTER_BY_NUMBER = "FILTER_BY_NUMBER";
export const FILTER_BY_CLIENT_NAME = "FILTER_BY_CLIENT_NAME";
export const FILTER_BY_DATE = "FILTER_BY_DATE";
export const FILTER_BY_TOTAL_WITHOUT_VAT = "FILTER_BY_TOTAL_WITHOUT_VAT";
export const APPLY_DOCUMENT_FILTERS = "APPLY_DOCUMENT_FILTERS"